### ISSUE TITLE
Change the `cdmlite` table structure: add `source_id`

### ISSUE THREAD

**Issue by agstephens** [glamod/glamod-ingest#12]
We decided to add the source ID to the CDM lite it allows lookups to the station config file and source config file. 

Simon sent an email outlining the data policy changes that may be needed in this release and the source ID would be required in the CDM lite to do this.

We need to insert a new column at the start of the cdmlite:

Column 1: source_id
Type: integer (lookup to `cdm_full.source_configuration::source`)

**Comment by agstephens** [comment]
Issue: how do we derive the Source ID when populating the cdmlite?

1. Land:

 - from cdmlite, get:
   - primary station id and scheme? - check old docs
 - from station_configuration, get:
   - source_id
 - put that in cdmlite

1)	We will need to add a source_id field to the CDM lite and then using the highlighted part of the observation_id (AFI0000OAHR-6-1973-01-01-00:00-85-12) to match with the combination of the primary_id and record_number in the station configuration table to find the source_id and populate the source_id field in the CDM_Lite.

2. Marine:
 -

**Comment by david-i-berry** [comment]
For marine the above is correct.

**Comment by agstephens** [comment]
Added `source_id` to cdmlite table: https://github.com/glamod/glamod-ingest/commit/f74719a97eb6653274dae1e4f4b7962f9fbfb366

**Comment by agstephens** [comment]
Closing this. Separate issues will track `restructure-land` and `restructure-marine` to include source_id.
