### ISSUE TITLE
Update restructure marine script to include source_id

### ISSUE THREAD

**Issue by agstephens** [glamod/glamod-ingest#19]
Update script `scripts/marine/restructure-marine.py`:

 -  from `header_table`, get:
  - `source_id`
 - put the `source_id` in cdmlite records

**Comment by SteveDonegan** [comment]
Working on local fork in https://github.com/SteveDonegan/glamod-ingest and have updated restructure-marine.py to include source_id.  Have tested and works.  Will merge back into main soon but need to ensure tracks original properly first.

**Comment by agstephens** [comment]
@SteveDonegan please do not merge yourself. Instead, create a Pull Request to request a merge and add me as a reviewer. I can then review and we can discuss any required changes before merging into master. 👍

**Comment by agstephens** [comment]
Fixed in Pull Request. Review before closing.

**Comment by agstephens** [comment]
Working
